export const ALL_REQUEST_BOOK_REQUEST = "ALL_REQUEST_BOOK_REQUEST";
export const ALL_REQUEST_BOOK_SUCCESS = "ALL_REQUEST_BOOK_SUCCESS";
export const ALL_REQUEST_BOOK_FAIL = "ALL_REQUEST_BOOK_FAIL";

export const NEW_REQUEST_BOOK_REQUEST = "NEW_REQUEST_BOOK_REQUEST";
export const NEW_REQUEST_BOOK_SUCCESS = "NEW_REQUEST_BOOK_SUCCESS";
export const NEW_REQUEST_BOOK_FAIL = "NEW_REQUEST_BOOK_FAIL";
export const NEW_REQUEST_BOOK_RESET = "NEW_REQUEST_BOOK_RESET";

export const NEW_REQUEST_DETAILS_REQUEST = "NEW_REQUEST_DETAILS_REQUEST";
export const NEW_REQUEST_DETAILS_SUCCESS = "NEW_REQUEST_DETAILS_SUCCESS";
export const NEW_REQUEST_DETAILS_FAIL = "NEW_REQUEST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";