export const ALL_EXCHANGE_BOOK_REQUEST = "ALL_EXCHANGE_BOOK_EXCHANGE";
export const ALL_EXCHANGE_BOOK_SUCCESS = "ALL_EXCHANGE_BOOK_SUCCESS";
export const ALL_EXCHANGE_BOOK_FAIL = "ALL_EXCHANGE_BOOK_FAIL";

export const NEW_EXCHANGE_BOOK_REQUEST = "NEW_EXCHANGE_BOOK_EXCHANGE";
export const NEW_EXCHANGE_BOOK_SUCCESS = "NEW_EXCHANGE_BOOK_SUCCESS";
export const NEW_EXCHANGE_BOOK_FAIL = "NEW_EXCHANGE_BOOK_FAIL";
export const NEW_EXCHANGE_BOOK_RESET = "NEW_EXCHANGE_BOOK_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";