export const ALL_SELL_BOOK_REQUEST = "ALL_SELL_BOOK_REQUEST";
export const ALL_SELL_BOOK_SUCCESS = "ALL_SELL_BOOK_SUCCESS";
export const ALL_SELL_BOOK_FAIL = "ALL_SELL_BOOK_FAIL";

export const NEW_SELL_BOOK_REQUEST = "NEW_SELL_BOOK_REQUEST";
export const NEW_SELL_BOOK_SUCCESS = "NEW_SELL_BOOK_SUCCESS";
export const NEW_SELL_BOOK_FAIL = "NEW_SELL_BOOK_FAIL";
export const NEW_SELL_BOOK_RESET = "NEW_SELL_BOOK_RESET"; 

export const NEW_SELL_DETAILS_REQUEST = "NEW_SELL_DETAILS_REQUEST";
export const NEW_SELL_DETAILS_SUCCESS = "NEW_SELL_DETAILS_SUCCESS";
export const NEW_SELL_DETAILS_FAIL = "NEW_SELL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";